image: Visual Studio 2017

version: 0.0.{build}

environment:
  MYGET_TOKEN:
    secure: tyLfoWjP8lgJNO8kBD1NQX4twHj/GVSwTUm/GG2yVAM3Ir3F3d7jzFEThgeFE96e

init:
  # Set "build version number" to "short-commit-hash" or when tagged to "tag name" (Travis style)
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
        Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_TAG_NAME.TrimStart("v"))"
      }
 
cache:
  - packages

build_script:
  - .paket\paket.exe restore
  - build.cmd Verify
  - build.cmd Extract
  - build.cmd Build
  - .paket\paket.exe pack --version %APPVEYOR_BUILD_VERSION% .

artifacts:
  - path: '*.nupkg'

deploy:
  - provider: NuGet
    server: https://www.myget.org/F/zenprotocol/api/v2/package
    api_key:
      secure: tyLfoWjP8lgJNO8kBD1NQX4twHj/GVSwTUm/GG2yVAM3Ir3F3d7jzFEThgeFE96e
    skip_symbols: true
    on:
      appveyor_repo_tag: true        # deploy on tag push only
