image: Visual Studio 2017

environment:
  MYGET_TOKEN:
    secure: deKebLALSKFBV5pPo4H6u1TZF0IC2Itlp9EpSACzlI1idYT+ldrkTXeGK5CniBQF

init:
  # Set "build version number" to "short-commit-hash" or when tagged to "tag name" (Travis style)
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
        Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_TAG_NAME.TrimStart("v"))"
      }
 
cache:
  - packages

build_script:
  - .paket\paket.exe restore
  - build.cmd
  - paket.cmd pack --version %APPVEYOR_BUILD_VERSION% .

artifacts:
  - path: '*.nupkg'

deploy:
  - provider: NuGet
    server: https://www.myget.org/F/zenprotocol/api/v2/package
    api_key:
      secure: deKebLALSKFBV5pPo4H6u1TZF0IC2Itlp9EpSACzlI1idYT+ldrkTXeGK5CniBQF
    skip_symbols: true
    on:
      appveyor_repo_tag: true        # deploy on tag push only
